name: 'Capture The Flag'

on:
  push:
    branches: [ "main" ]

jobs:
  clients:
    name: 'Test Clients'
    runs-on: 'ubuntu-22.04'

    strategy:
      matrix:
        client: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run Clients
        run: 'python client_${{ matrix.client }}.py'

  submit:
    name: 'Test Scorebot'
    runs-on: 'ubuntu-22.04'
    needs: clients

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Submit Flags
        run: 'python submit.py -u test'
